.devops/pagopa-code-review-pipelines.yml, .devops/pagopa-deploy-pipelines.yml
=> fix: fix config for pipelines

.devops/azure-templates/setup-env.yml, .devops/pagopa-code-review-pipelines.yml, .devops/pagopa-deploy-pipelines.yml
=> feat: add ci-cd pipelines

.devops/pagopa-code-review-pipelines.yml, .prettierrc.json, README.md, env.sh, jest.config.js, package.json, src/index.html, src/utils/urlUtilities.ts
=> fix: minor code from main

.devops/pagopa-deploy-pipelines.yml
=> feat: CHK-1981 update azurecli 2

.devops/azure-templates/setup-env.yml, .devops/pagopa-code-review-pipelines.yml, .devops/pagopa-deploy-pipelines.yml, env.sh
- Unuseful env variables removed from pipelines
- Useful ones added and valued
- Updating the env.sh bash script to output a .env file (used by parcel when building)
The right env variable values are necessary to make the front end acts correctly by environment
Will be tested via deploy and code review pipeline output and testing the dev environment
=> fix: updating env variables on pipelines

.devops/azure-templates/setup-env.yml, .devops/pagopa-code-review-pipelines.yml, .devops/pagopa-deploy-pipelines.yml
The npg sdk url miss from the pipelines. With this PR we add the ref and a default value.
Bundle miss the conf and breaks the render
=> Add npg_sdk_url to envs confs

.devops/azure-templates/setup-env.yml
Found a typo in the npg sdk url
=> Typo npg sdk url value

jest.config.js, package.json, src/utils/__tests__/api.test.ts, src/utils/__tests__/npg.test.ts, src/utils/__tests__/validators.test.ts, src/utils/api/npg/index.ts, src/utils/testUtils.ts, src/utils/validators.tsx
Added a function to validate the response from the /wallets/:walletId/sessions.
When validation fails a generic error modal shows up.
With a partial or incomplete response it's useless to build the card onboarding form. It's better to give users a feedback (error modal)
Trough unit tests and a real test using the wallet-be-mock and simulating a partial response
=> [CHK-2081]

.devops/azure-templates/setup-env.yml, .devops/pagopa-deploy-pipelines.yml
Added WALLET_GDI_CHECK_TIMEOUT into deploy pipeline
=> fix: added env variable WALLET_GDI_CHECK_TIMEOUT

.devops/azure-templates/setup-env.yml, .devops/pagopa-deploy-pipelines.yml, .proxyrc.js, README.md, env.example, src/config.ts, src/utils/__tests__/api.test.ts, src/utils/__tests__/hooks.test.ts, src/utils/__tests__/npg.test.ts, src/utils/api/pm/index.tsx
Modified outcome with value 14 in case of http 401 status from pm during api wallet/cc
The change was made to handle 401 from PM.
=> CHK-2131: feat: added logic and configuration for use new wallet api outcome

api-spec/pm-spec.json, package.json
Added new local pm openapi specification.
- Fixed date problem into WalletV2 object
- Modified **/v3/paypal/searchPSP** to **/v3/paypal/psps**
=> feat: create local pm openapi specification

src/routes/Cards.tsx, src/routes/PaypalPage.tsx
This PR add two translated-labels to some routes
=> [bug] Missed translate

src/features/onboard/components/IframeCardForm.tsx, src/routes/PaypalPage.tsx, src/routes/models/routeModel.ts, src/routes/pm/BPay.tsx, src/routes/pm/Cards.tsx, src/utils/__tests__/api.test.ts, src/utils/__tests__/npg.test.ts, src/utils/__tests__/paypal.test.ts, src/utils/__tests__/validators.test.ts, src/utils/api/index.tsx, src/utils/api/npg/index.ts, src/utils/api/pm/index.tsx, src/utils/api/pm/paypal.ts, src/utils/api/utils.ts, src/utils/testUtils.ts, src/utils/urlUtilities.ts, src/utils/validators.tsx
- all api calls are passed to `matchApiStatus` to handle responses status code
- api are now returning an `Either<ErrorType, T>`
- Increased unit test numbers and coverage
- `validateApi` function to check validation
- `matchApiStatus `to validate api response status
- `badStatusHandler` to handle errors or navigation on bad status codes
- some refactoring
- unit tests
- visual testing
=> [CHK-2155] api status handling

package.json
The scope of this PR is to restore restore the right api specs pointer of webview-payment-wallet-api client and definitions
This change is essential to have always the webview-payment-wallet-api client and definitions updated
Tested building the client (yarn generate) and running the FE locally
=> [CHK-2210] Restoring the webview-payment-wallet-api api specs pointer

.proxyrc.js, env.example, package.json, src/features/onboard/components/IframeCardForm.tsx, src/routes/Apm.tsx, src/routes/Cards.tsx, src/routes/Outcome.tsx, src/utils/__tests__/api.test.ts, src/utils/__tests__/npg.test.ts, src/utils/__tests__/validators.test.ts, src/utils/api/npg/index.ts, src/utils/testUtils.ts, src/utils/validators.tsx
- POST /wallet/$id/sessions API integration
- redirect to sessionData.redirectUrl from POST /wallet/$id/sessions API integration API response
- unit test update and fix
The confirm phase ends the apm onboarding flow
Tested locally pointing to dev environment, via unit e2e automatic and manual tests
=> [CHK-2239] APM onboarding: confirm phase

src/components/commons/Layout.tsx
- Sets page vertical padding to 0.
Set vertical padding to 0 since pages are going to be used as webviews. 
- Visual testing
|375x812|
|---------|
=> Fix [CKH-2151]: Removes layout vertical padding

src/components/FormButtons/FormButtons.tsx
Fix style as expected by designers
- drop mobile override
=> [CHK-2150] Set style to button as expected

api-spec/pm-spec.json, src/routes/models/routeModel.ts, src/utils/__tests__/urlUtili.test.ts, src/utils/validators.tsx
- add outcome 15 for conflict (i.e already onboarded wallet)
The goal of this PR is to redirect with outcome 15 for already onboard card, valid only for Payment Manager flow.
=> feat: add outcome 15 for already onboarded

src/components/commons/BpayAccountItem.tsx
The goal of this PR is to set bpay logo url given the environment.
=> fix: CHK-2347 bpay logo URL given ENV

.devops/azure-templates/setup-env.yml, .devops/pagopa-deploy-pipelines.yml, README.md, env.example, src/App.tsx, src/config.ts, src/features/onboard/components/CustomSwitch.tsx, src/features/onboard/components/IframeCardForm.tsx, src/routes/Cards.tsx, src/routes/models/routeModel.ts, src/translations/it/translations.ts
- Added a new route (payment/creditcard) to manage a payment and the save method option
- Added a new env variable (WALLET_ONBOARD_SWITCH_ON_PAYMENT_PAGE) as a feature flag for show/hidden the save method's toggle
this feature allows IO app users to pay and at the same time save the method (eventually) in their own wallet for future payments
Tested locally through the local front end web server. Still not possible to test the full flow
=> [CHK-2365] save method's toggle on wallet payment page

.devops/azure-templates/setup-env.yml, .devops/pagopa-code-review-pipelines.yml, .devops/pagopa-deploy-pipelines.yml, README.md, env.example, src/config.ts, src/utils/__tests__/urlUtili.test.ts, src/utils/urlUtilities.ts
- The redirect url built with redirectToIoAppForPayment utility function has been updated
- The relative unit tests has been updated
The redirect url was wrong
Locally using the FE local development server and the wallet-be-mock as BE service
=> [CHK-2426]: cc payment with onboarding, redirect url update

src/utils/__tests__/urlUtili.test.ts, src/utils/urlUtilities.ts
Fixed redirect path for app io
=> fix: redirect path

src/routes/Apm.tsx, src/routes/pm/BPay.tsx, src/utils/__tests__/urlUtili.test.ts, src/utils/urlUtilities.ts
Return the first id of bpay walletlistids to redirect success outcome
=> [CHK-2392] return first id from walletId list for bpay

src/routes/pm/BPay.tsx, src/utils/__tests__/urlUtili.test.ts, src/utils/urlUtilities.ts
manage numeric and string idWallet. Use bpay idWallet in place of uid
=> [CHK-2392] manage numeric and string idWallet. Use bpay idWallet in place of uid

src/components/commons/PageContainer.tsx
- Adds a title top margin of 24px in the PageContainer component
- Visual testing
=> Fix [CHK-2489] Increase pages margin to 24px

src/routes/pm/BPay.tsx
Show canceled by user message when user cancel bpay onboarding
=> [CHK-2543] fix bpay onboarding cancel

src/routes/models/routeModel.ts, src/routes/pm/BPay.tsx, src/utils/__tests__/api.test.ts, src/utils/api/npg/index.ts, src/utils/api/pm/index.tsx
=> [CHK-2569] refactor(bpay): redirect with outcome 16 if no account is available

src/routes/Outcome.tsx
add walletId in outcome redirect for Outcome page
In Outcome page pass walletId if availabale in outcome redirect function
Bug fixing for App IO integration
=> [CHK-2730] fix(outcome): walletId missing

src/routes/Outcome.tsx
Set walletId in success url only for onboarding success
=> [CHK-2737] fix(outcomeurl): walletId present only for success case

src/routes/Apm.tsx
Add new react state to disable APM onboarding form during loading
=> fix: [CHK-2816] Disabled form during submitting process

.devops/pagopa-deploy-pipelines.yml
=> feat(pipeline): CHK-2947 deploy on new cdn pay-wallet domain

.devops/pagopa-deploy-pipelines.yml
=> feat(pipeline): CHK-2947 enable prod config

.devops/pagopa-deploy-pipelines.yml
=> fix: params

src/translations/it/translations.ts
Update translation files to serve strings when NPG returns exception in validation
=> [#CHK-2962] Add translation for NPG validation error

src/features/onboard/components/IframeCardField.tsx, src/features/onboard/components/IframeCardForm.tsx, src/utils/buildConfig.ts
* use callback + prop to set loading state in card onboarding form
This PR exploits a new feature of the NPG XPay Build SDK that allows us to more accurately time loading state in case of card onboarding
=> [CHK-3000] feat: use callback + prop to set loading state in card onboarding form

src/components/FormButtons/FormButtons.tsx, src/routes/Apm.tsx
Add id to radio button for psp selectionId and form button for testing automation purpose
=> add id to radio button to select psp

src/index.html
- add meta tag to disable  cache only for index.html
The goal of the PR is to disable any caching on the `index.html` page, which is causing 404 errors due to outdated JS references. This fix is necessary to resolve issues of 'blank pages.' In addition to this fix, we will also intervene on the CDN to perform a purge on the individual resource.
=> fix: CHK-3174 disable cache only for index.html

.devops/pagopa-deploy-pipelines.yml
-  increase gdi check timeout
The goal of this PR is to increase gdi-check step timeout before polling for the transaction outcome  begins.
=> chore: increase gdi check timeout

package.json
Set openapi ref to pay-wallet-app domain
=> [CHK-3629] fix openapi refs

package.json, src/routes/Outcome.tsx
- add null-undefined check for outcome received
- fix code coverage
This PR solves a problem with success outcome that is converted to generic error
=> [CHK-3241] fix: add null-undefined check for outcome

package.json
Update package json to refers new openapi definition for outcome code update
=> [CHK-3573] update outcomes definition

.devops/pagopa-code-review-pipelines.yml
- updated versions for pipeline tasks which generated deprecation warnings on remote build and deploy processes
This update was needed to prevent future execution failures on code review and deploy pipelines
- Pipeline jobs executed successfully and without deprecation warnings
=> [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions

jest.config.js
- update coverage config
The goal of this PR is to add tsx file to test and covergare configuration.
=> chore: CHK-4060 enable test for tsx file

jest.config.js
=> chore: CHK-4061 exclude code related to PM

jest.config.js, jest.setup.js, src/features/onboard/models/npgModel.ts, src/utils/__tests__/api.test.ts, src/utils/__tests__/buildConfig.test.ts, src/utils/__tests__/errors/errorsModel.test.ts, src/utils/__tests__/eventListener.test.ts, src/utils/api/config.tsx
- Added unit tests to cover classes under utils directory
- Add config file for shared mock/env usage
This change was needed to provide more test coverage for the utils directory classes, since some of them were partially covered and others were untested.
- Ran unit tests locally in a Jest environment verifying coverage .
- Examined the generated coverage reports (HTML/LCOV) to confirm that previously uncovered code portions are now covered adequately.
Before:
After:
=> [CHK-4063] add unit tests for utils directory

.eslintrc.js, jest.config.js, package.json, src/routes/__tests__/Apm.test.tsx, src/routes/__tests__/Cards.test.tsx, src/routes/__tests__/GdiCheck.test.tsx, src/routes/__tests__/Outcome.test.tsx, src/routes/__tests__/routeModel.test.tsx, src/utils/svgMock.ts, yarn.lock
- added unit tests for all react routes/pages
=> [CHK-4062] feat(test-pages): add unit tests for routes/pages

src/translations/de/translations.json, src/translations/en/translations.json, src/translations/lang.ts
This PR adds english and german localization for strings
IO users can set their app in english and german too
N/A
=> feat: aggiunta traduzione wallet per le lingue inglese e tedesco

src/components/__tests__/commons/InformationModal.test.tsx, src/components/commons/InformationModal.tsx, src/routes/Cards.tsx, src/routes/__tests__/Cards.test.tsx, src/translations/de/translations.json, src/translations/en/translations.json, src/translations/it/translations.json
Implemented a new modal to prevent user from misinputting when adding a card to the payment methods.
The change was needed due to the high number of tickets issued about a recurring error.
Through manual testing and unit tests.
=> (feature): [PIDM-905] CVV Modal for Amex Cards

src/translations/de/translations.json, src/translations/en/translations.json, src/translations/it/translations.json
Fix text spaces and new lines
Fix text spaces and new lines
Local test
=> fix: modal spaces and new lines
